// Auto-generated by update_lerobot_definitions.py
#include <map>
#include <string>

inline std::map<std::string, std::string> get_lerobot_definitions() {
    return {
        {"dataset", "-local-files-only` (in the following case the dataset will be searched for in `./my_local_data_dir/lerobot/pusht`)"},
        {"conda", "y -n lerobot python=3.10"},
        {"hf_dataset", "a Hugging Face dataset (backed by Arrow/parquet). Typical features example:"},
        {"action", "goal position of an arm joints (for instance)"},
        {"observation", "[-1, -0.5, -0.2, 0]}`  one can retrieve, for a given index, 4 frames: 3 "previous" frames 1 second, 0.5 seconds, and 0.2 seconds before the indexed frame, and the indexed frame itself (corresponding to the 0 entry). See example [1_load_lerobot_dataset.py](examples/1_load_lerobot_dataset.py) for more details on `delta_timestamps`."},
        {"robot", "world robotics on the most affordable and capable robots out there."},
        {"LeRobot", "logo-thumbnail.png">"},
    };
}
